### ISSUE TITLE
Error on source code minification

### ISSUE THREAD

**Issue by jmike** [gertn/ng-i18n#1]
**What steps will reproduce the problem?**
1. Download latest ng-i18n module.
2. Add dependencies to the main angular app.
3. Minify using uglify.js having the mangle option enabled.

**What is the expected result?**
I think mangling and minifying should not affect the module.

**What happens instead?**
I am getting the following error on source code minification.

```
Uncaught Error: Unknown provider: e from ngI18nService 
```

**Additional info**
Without mangle being enabled the source code runs fine. So I am pretty sure I am not doing something wrong with angular.js or any other loaded module.

PS> Many thanks for the wonderful internationalization module.

**Comment by gertn** [comment]
Should be fixed, can you verify this so I can close the issue.

**Comment by jmike** [comment]
Hi,

Thank you very much for the quick fix. It works like a charm.

Cheers,
