### ISSUE TITLE
Karma test breaks

### ISSUE THREAD

**Issue by kdekooter** [gertn/ng-i18n#3]
When running a karma test that loads the app like so:

```
beforeEach(angular.mock.module('theApp'));
```

Grunt barfs:

```
    Error: Unexpected request: GET i18n/resourceBundle.json
    No more request expected
        at $httpBackend (/Users/kees/workspaces/../app/components/angular-mocks/angular-mocks.js:6)
        at sendReq (/Users/kees/../app/components/angular/angular.js:6)
        at $http (/Users/kees/workspaces/../app/components/angular/angular.js:6)
        at get (/Users/kees/workspaces/../app/scripts/lib/ng-i18n-0.2.1.js:6)
```

How can we make the test pass when ng-i18n is included?

**Comment by gertn** [comment]
something like the following:
var $httpBackend, resourceBundle;
beforeEach(inject(function ($injector) {
            $httpBackend = $injector.get('$httpBackend');
            resourceBundle= {"key1":'value1', "key2":'value2'};
            $httpBackend.when("GET", 'i18n/resourceBundle.json').respond(resourceBundle);
 }));

**Comment by kdekooter** [comment]
Excuse my n00bness, but do I have to add this to every test then?

**Comment by gertn** [comment]
I don't have enough context what you are trying to test? Is it a controller unit test, a service test, ...?
Can I take a look at your code and test?

**Comment by kdekooter** [comment]
I was loading the entire app in my unit test. Which is bad practice I assume. I was able to narrow it down now. We can close the issue. Thanks for your support!
