### ISSUE TITLE
Error: Unknown provider: ngI18nResourceBundleProvider <- ngI18nResourceBundle

### ISSUE THREAD

**Issue by campa** [gertn/ng-i18n#6]
Hi 

I'm trying using your ng lib, but I have the follow error:
"Error: Unknown provider: ngI18nResourceBundleProvider <- ngI18nResourceBundle"

Please, Can you suggest me things on configuration or others to check ?

Thx in advance.
Stefano

**Comment by gertn** [comment]
When you declare your app you have to load the ngI18n module:

``` javascript
 var yourApp = angular.module('yourApp',['ngI18n', ... {other includes}]);
    yourApp.value('ngI18nConfig', {
        defaultLocale: 'en',
        supportedLocales: ['en', 'nl']
    });
```

Follow the 'How to use' in the README.md
https://github.com/gertn/ng-i18n/blob/master/README.md

**Comment by campa** [comment]
Solved, Thanks !!
I have been wrong "declaring" my module ...
